name: Run Naver Maemul Crawler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'  # 매일 한국시간 자정 (UTC 15:00)

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the crawler script
        env:
          NID_AUT: ${{ secrets.NID_AUT }}
          NID_SES: ${{ secrets.NID_SES }}
        run: |
          python naver_maemul_hwaseong.py

      - name: Set remote URL with PAT token
        run: |
          git remote set-url origin https://${{ secrets.NAVER_NEWS }}@github.com/lyh9003/maemul.git
          git remote -v

      - name: Commit trade info CSV
        run: |
          git config --local user.email "lyh9003@gmail.com"
          git config --local user.name "LeeYongHoon"
          git add trade_info_*.csv
          git commit -m "Update trade info CSV file [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
