name: Naver Maemul Action Automation

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run naver_maemul_action.py
        run: python naver_maemul_action.py

      - name: Commit trade info CSV
        run: |
          git config --local user.email "lyh9003@gmail.com"
          git config --local user.name "LeeYongHoon"
          git add trade_info_*.csv
          git commit -m "Update trade info CSV file [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
