name: Run Naver News Crawler

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 실행 (원하는 시간대로 수정 가능)

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the crawler script
        run: python naver_maemul_action.py
        # 크롤러 스크립트 파일 이름이 naver_maemul_action.py 인지 확인

      - name: Set remote URL with PAT token
        run: |
          git remote set-url origin https://${{ secrets.NAVER_NEWS }}@github.com/lyh9003/maemul.git
          git remote -v
          
      - name: Commit trade info CSV
        run: |
          git config --local user.email "lyh9003@gmail.com"
          git config --local user.name "LeeYongHoon"
          git add trade_info_*.csv
          git commit -m "Update trade info CSV file [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
